// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCart = "Cart"

// Cart mapped from table <Cart>
type Cart struct {
	ProductID int32 `gorm:"column:ProductID;primaryKey" json:"ProductID"`
	UserID    int32 `gorm:"column:UserID;primaryKey" json:"UserID"`
	Quantity  int32 `gorm:"column:Quantity;not null" json:"Quantity"`
	Price     int32 `gorm:"column:Price;not null" json:"Price"`
}

// TableName Cart's table name
func (*Cart) TableName() string {
	return TableNameCart
}
