// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDiscount = "Discount"

// Discount mapped from table <Discount>
type Discount struct {
	DiscountID  int32     `gorm:"column:DiscountID;primaryKey;autoIncrement:true" json:"DiscountID"`
	Percent     float64   `gorm:"column:Percent;not null" json:"Percent"`
	CreatedAt   time.Time `gorm:"column:CreatedAt" json:"CreatedAt"`
	ExpiredDate time.Time `gorm:"column:ExpiredDate" json:"ExpiredDate"`
	ProductID   int32     `gorm:"column:ProductID;not null" json:"ProductID"`
}

// TableName Discount's table name
func (*Discount) TableName() string {
	return TableNameDiscount
}
