// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameInvoice = "Invoice"

// Invoice mapped from table <Invoice>
type Invoice struct {
	InvoiceID  int32     `gorm:"column:InvoiceID;primaryKey;autoIncrement:true" json:"InvoiceID"`
	UserID     int32     `gorm:"column:UserID;not null" json:"UserID"`
	TotalPrice int32     `gorm:"column:TotalPrice" json:"TotalPrice"`
	CreatedAt  time.Time `gorm:"column:CreatedAt" json:"CreatedAt"`
}

// TableName Invoice's table name
func (*Invoice) TableName() string {
	return TableNameInvoice
}
