// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePost = "Post"

// Post mapped from table <Post>
type Post struct {
	PostID           int32     `gorm:"column:PostID;primaryKey;autoIncrement:true" json:"PostID"`
	CategoryID       int32     `gorm:"column:CategoryID;not null" json:"CategoryID"`
	Title            string    `gorm:"column:Title;not null" json:"Title"`
	ShortDescription string    `gorm:"column:ShortDescription;not null" json:"ShortDescription"`
	Content          string    `gorm:"column:Content;not null" json:"Content"`
	Thumbnail        string    `gorm:"column:Thumbnail;not null" json:"Thumbnail"`
	CreatedAt        time.Time `gorm:"column:CreatedAt" json:"CreatedAt"`
	UpdatedAt        time.Time `gorm:"column:UpdatedAt" json:"UpdatedAt"`
	DeletedAt        time.Time `gorm:"column:DeletedAt" json:"DeletedAt"`
	Slug             string    `gorm:"column:Slug;not null" json:"Slug"`
	Author           string    `gorm:"column:Author;not null" json:"Author"`
	UserID           int32     `gorm:"column:UserID;not null" json:"UserID"`
}

// TableName Post's table name
func (*Post) TableName() string {
	return TableNamePost
}
