// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePostComment = "PostComment"

// PostComment mapped from table <PostComment>
type PostComment struct {
	CommentID int32     `gorm:"column:CommentID;primaryKey;autoIncrement:true" json:"CommentID"`
	UserID    int32     `gorm:"column:UserID;not null" json:"UserID"`
	PostID    int32     `gorm:"column:PostID;not null" json:"PostID"`
	Content   string    `gorm:"column:Content;not null" json:"Content"`
	Parent    int32     `gorm:"column:Parent" json:"Parent"`
	CreatedAt time.Time `gorm:"column:CreatedAt" json:"CreatedAt"`
	IsHiden   bool      `gorm:"column:IsHiden" json:"IsHiden"`
}

// TableName PostComment's table name
func (*PostComment) TableName() string {
	return TableNamePostComment
}
