// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePostCategory = "PostCategory"

// PostCategory mapped from table <PostCategory>
type PostCategory struct {
	CategoryID   int32  `gorm:"column:CategoryID;primaryKey;autoIncrement:true" json:"CategoryID"`
	CategoryName string `gorm:"column:CategoryName;not null" json:"CategoryName"`
	Slug         string `gorm:"column:Slug;not null" json:"Slug"`
}

// TableName PostCategory's table name
func (*PostCategory) TableName() string {
	return TableNamePostCategory
}
