// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProduct = "Product"

// Product mapped from table <Product>
type Product struct {
	ProductID   int32     `gorm:"column:ProductID;primaryKey;autoIncrement:true" json:"ProductID"`
	CategoryID  int32     `gorm:"column:CategoryID;not null" json:"CategoryID"`
	ProductName string    `gorm:"column:ProductName;not null" json:"ProductName"`
	SellPrice   int32     `gorm:"column:SellPrice;not null" json:"SellPrice"`
	Description string    `gorm:"column:Description" json:"Description"`
	CreatedAt   time.Time `gorm:"column:CreatedAt" json:"CreatedAt"`
	UpdatedAt   time.Time `gorm:"column:UpdatedAt" json:"UpdatedAt"`
	DeletedAt   time.Time `gorm:"column:DeletedAt" json:"DeletedAt"`
	Slug        string    `gorm:"column:Slug;not null" json:"Slug"`
	Stock       bool      `gorm:"column:Stock;default:true" json:"Stock"`
}

// TableName Product's table name
func (*Product) TableName() string {
	return TableNameProduct
}
