// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProductComment = "ProductComment"

// ProductComment mapped from table <ProductComment>
type ProductComment struct {
	CommentID int32     `gorm:"column:CommentID;primaryKey;autoIncrement:true" json:"CommentID"`
	UserID    int32     `gorm:"column:UserID;not null" json:"UserID"`
	ProductID int32     `gorm:"column:ProductID;not null" json:"ProductID"`
	Content   string    `gorm:"column:Content;not null" json:"Content"`
	Parent    int32     `gorm:"column:Parent" json:"Parent"`
	CreatedAt time.Time `gorm:"column:CreatedAt" json:"CreatedAt"`
	IsHiden   bool      `gorm:"column:IsHiden" json:"IsHiden"`
}

// TableName ProductComment's table name
func (*ProductComment) TableName() string {
	return TableNameProductComment
}
