// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameProductImage = "ProductImage"

// ProductImage mapped from table <ProductImage>
type ProductImage struct {
	ImageID   int32  `gorm:"column:ImageID;primaryKey;autoIncrement:true" json:"ImageID"`
	Link      string `gorm:"column:Link;not null" json:"Link"`
	ProductID int32  `gorm:"column:ProductID;not null" json:"ProductID"`
}

// TableName ProductImage's table name
func (*ProductImage) TableName() string {
	return TableNameProductImage
}
