// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRole = "Role"

// Role mapped from table <Role>
type Role struct {
	RoleID   string `gorm:"column:RoleID;primaryKey" json:"RoleID"`
	RoleName string `gorm:"column:RoleName;not null" json:"RoleName"`
}

// TableName Role's table name
func (*Role) TableName() string {
	return TableNameRole
}
