// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUser = "User"

// User mapped from table <User>
type User struct {
	UserID    int32  `gorm:"column:UserID;primaryKey;autoIncrement:true" json:"UserID"`
	RoleID    string `gorm:"column:RoleID;not null" json:"RoleID"`
	Username  string `gorm:"column:Username;not null" json:"Username"`
	Email     string `gorm:"column:Email;not null" json:"Email"`
	Password  string `gorm:"column:Password;not null" json:"Password"`
	Phone     string `gorm:"column:Phone;not null" json:"Phone"`
	Address   string `gorm:"column:Address;not null" json:"Address"`
	Avatar    string `gorm:"column:Avatar" json:"Avatar"`
	Balance   int32  `gorm:"column:Balance;not null" json:"Balance"`
	IsBlocked bool   `gorm:"column:IsBlocked" json:"IsBlocked"`
	Slug      string `gorm:"column:Slug" json:"Slug"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
